### ISSUE TITLE
Significant challenges trying to use Node 16 due to `nexe` dependency

### ISSUE THREAD

**Issue by contrarianchris** [pulumi/pulumi-component-provider-ts-boilerplate#17]
### What happened?

When using Node 16 and running through the example immediately after cloning the template, the following error is thrown trying to run `pulumi up`.

```
❯ pulumi up
Previewing update (test)

View Live: https://app.pulumi.com/contrarianchris/simple/test/previews/d80785c8-a1a4-4de3-8d8a-e87c7e94e9b5

     Type                     Name           Plan       Info
 +   pulumi:pulumi:Stack      simple-test    create     11 messages
     └─ pulumi:providers:xyz  default_0_0_1             1 error

Diagnostics:
  pulumi:pulumi:Stack (simple-test):
    TypeError: Cannot read property '1' of undefined
        at isFileType (fs.js:193:19)
        at Object.readFileSync (fs.js:380:16)
        at readFileSync (/home/chris/laybuy/pulumi-laybuy-aws/bin/pulumi-resource-xyz:233:55)
        at main (/home/chris/laybuy/pulumi-laybuy-aws/bin/build/index.js:384097:49)
        at /home/chris/laybuy/pulumi-laybuy-aws/bin/build/index.js:384106:1
        at /home/chris/laybuy/pulumi-laybuy-aws/bin/build/index.js:384108:3
        at Object.<anonymous> (/home/chris/laybuy/pulumi-laybuy-aws/bin/build/index.js:384111:12)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)

  pulumi:providers:xyz (default_0_0_1):
    error: could not read plugin [/home/chris/laybuy/pulumi-laybuy-aws/bin/pulumi-resource-xyz] stdout: EOF

```

### Steps to reproduce

1. Clone the template repo.
2. Follow the steps in the "Build and Test" section of the README...
```
# Build and install the provider
make install_provider

# Regenerate SDKs
make generate

# Ensure the pulumi-provider-xyz script is on PATH
$ export PATH=$PATH:$PWD/bin

# Test Node.js SDK
$ make install_nodejs_sdk
$ cd examples/simple
$ yarn install
$ yarn link @pulumi/xyz
$ pulumi stack init test
$ pulumi config set aws:region us-east-1
$ pulumi up
```

### Expected Behavior

Running `pulumi up` should complete successfully, with a working provider binary.

### Actual Behavior

The provider fails during `pulumi update` with the following error...
```
pulumi:providers:xyz (default_0_0_1):
    error: could not read plugin [/home/chris/laybuy/pulumi-laybuy-aws/bin/pulumi-resource-xyz] stdout: EOF
```

Further investigation found Node 14.15.3 hardcoded in the included Makefile, while our target is Node 16.13.0.
Looking through various issues filed in the `nexe` project it appears using the `--build` flag enables using newer Node versions. 

Updating the Makefile with the following changes...
```
override target := "16.13.0"

...

build_provider:: ensure
	cp ${SCHEMA_PATH} provider/cmd/${PROVIDER}/
	pushd provider/cmd/${PROVIDER}/ && \
		yarn install && \
	popd && \
	rm -rf build && npx --package @vercel/ncc ncc build provider/cmd/${PROVIDER}/index.ts -o build && \
	sed -i.bak -e "s/\$${VERSION}/$(VERSION)/g" ./build/index.js && \
	rm ./build/index.js.bak && \
	rm -rf ./bin && mkdir bin && \
	npx nexe build/index.js -r build/schema.json -t $(target) -o bin/${PROVIDER} --build

```

and running `make install_provider` then fails with the following error...
```
ℹ nexe 4.0.0-beta.19
✔ Included 0 file(s)
✔ Already downloaded...
✔ Configuring node build: --dest-cpu=x64
✔ Finished in 1.088s
Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
make: *** [Makefile:31: build_provider] Error 1
```

More research reveals the need to use the `--python` flag to provide `nexe` the location of Python as Node 16 dropped support for Python 2. An additional change to the Makefile...
```
build_provider:: ensure
	cp ${SCHEMA_PATH} provider/cmd/${PROVIDER}/
	pushd provider/cmd/${PROVIDER}/ && \
		yarn install && \
	popd && \
	rm -rf build && npx --package @vercel/ncc ncc build provider/cmd/${PROVIDER}/index.ts -o build && \
	sed -i.bak -e "s/\$${VERSION}/$(VERSION)/g" ./build/index.js && \
	rm ./build/index.js.bak && \
	rm -rf ./bin && mkdir bin && \
	npx nexe build/index.js -r build/schema.json -t $(target) -o bin/${PROVIDER} --build --python=python3
```

This allows the `nexe` build command to progress.
```
ℹ nexe 4.0.0-beta.19
✔ Included 0 file(s)
✔ Already downloaded...
⠼ Compiling Node...
```

However, it then became clear that `nexe` is compiling Node 16.13.0 from source and building it in the local environment. After over 30 minutes I cancelled the process. Some reading suggests average Node build times are easily over an hour, which is just not desirable for local development.

### Versions used

```
CLI
Version      3.29.1
Go Version   go1.17.8
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
xyz     0.0.1

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs (/home/chris/.nvm/versions/node/v16.13.0/bin/node v16.13.0)

Current Stack: test

Found no resources associated with test

Found no pending operations associated with test

Backend
Name           pulumi.com
URL            https://app.pulumi.com/contrarianchris
User           contrarianchris
Organizations  contrarianchris, laybuy

NAME            VERSION
@pulumi/pulumi  3.30.0
@types/node     10.17.60
```

### Additional context

I also needed to specify the `SHELL := /bin/bash` variable in the Makefile, as per https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/issues/16

Additionally, `nexe` doesn't seem to be very active as a project anymore. The more recent beta versions do support newer Node versions through the compile option, but the last stable release that doesn't support newer Node versions was nearly 2 years ago. 
https://www.npmjs.com/package/nexe

There has been talk of publishing missing binaries and even a v5 rewrite for over a year without much progress.
https://github.com/nexe/nexe/issues/754
https://github.com/nexe/nexe/issues/843

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by alexanderniebuhr** [comment]
Is there any reason why not using [vercel/pkg](https://github.com/vercel/pkg)
It seems to be used for the same kind of tool, and looks updated more regular, with support for newest node versions

**Comment by contrarianchris** [comment]
@alexanderniebuhr There is some history in https://github.com/pulumi/pulumi/issues/7009. It looks like `pkg` struggled with some of what was being done inside the package, at least back then.

**Comment by stack72** [comment]
Folks we are in the process of moving to pkg as we all speak :)

**Comment by stack72** [comment]
Another small update here - we believe we have sorted out what we need to do here and will migrate this boiler plate to use the new way this week

**Comment by danielrbradley** [comment]
`pkg` is now implemented and working correctly on awsx 1.0.0-beta.7 release, along with a change which will be release in the next `@pulumi/pulumi` release.
