### ISSUE TITLE
Generated binary throwing error when compiled with pkg

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-component-provider-ts-boilerplate#27]
When switching to using pkg to build the binary I get the following error when running the plugin. Not sure what is causing this or why it would even need the node inspector. Maybe there is some [dependency](https://github.com/pulumi/pulumi-aws-static-website/blob/main/provider/cmd/pulumi-resource-aws-static-website/package.json) that is part of the project that is causing this to be thrown.

```
error: [runtime] Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
        at new NodeError (node:internal/errors:372:5)
        at node:inspector:23:9
        at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
        at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
        at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
        at Function.Module._load (node:internal/modules/cjs/loader:804:15)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at Module.require (pkg/prelude/bootstrap.js:1855:31)
        at require (node:internal/modules/cjs/helpers:102:18)
        at /snapshot/pulumi-resource-aws-static-website/node_modules/@pulumi/pulumi/runtime/closure/v8Hooks.js:52:62
```

I ended up reverting back to using nexe for the time being since it is working.

**Comment by danielrbradley** [comment]
This is thrown by older versions of the @pulumi/pulumi package. Upgrading to the latest version should resolve the warning being printed.
